#!/usr/bin/env python

import sys
import csv

csvfile = csv.reader(sys.stdin, delimiter=';')
assert list(next(csvfile)) == ["team_home_name", "team_away_name", "game_starts_at" ]  # consume and check header

rows = []
for row in csvfile:
    team1, team2, startTime = row
    rows.append( f"( '{team1}', '{team2}', '{startTime}' )" )  # TODO: fix possible SQL injection
    # not too much of a problem as long we can trust data.csv

print("INSERT INTO games ( team_home, team_away, starts_at ) VALUES")

print(',\n'.join(rows))

print(";")
